const content = [
	{
		image: '/img/myWeb.jpg',
		header: 'My Website',
		about: 'Following projects showcase my skills and experience through real-world examples of my work. Each project is briefly described with links to code repositories and live demos in it. It reflects.',
		liveLink: 'https://youtube.com',
		github: 'https://youtube.com',
	},
	{
		image: '/img/myWeb.jpg',
		header: 'My Website',
		about: 'Following projects showcase my skills and experience through real-world examples of my work. Each project is briefly described with links to code repositories and live demos in it. It reflects.',
		liveLink: 'https://youtube.com',
		github: 'https://youtube.com',
	},
	{
		image: '/img/myWeb.jpg',
		header: 'My Website',
		about: 'Following projects showcase my skills and experience through real-world examples of my work. Each project is briefly described with links to code repositories and live demos in it. It reflects.',
		liveLink: 'https://youtube.com',
		github: 'https://youtube.com',
	},
	{
		image: '/img/myWeb.jpg',
		header: 'My Website',
		about: 'Following projects showcase my skills and experience through real-world examples of my work. Each project is briefly described with links to code repositories and live demos in it. It reflects.',
		liveLink: 'https://youtube.com',
		github: 'https://youtube.com',
	},
	{
		image: '/img/myWeb.jpg',
		header: 'My Website',
		about: 'Following projects showcase my skills and experience through real-world examples of my work. Each project is briefly described with links to code repositories and live demos in it. It reflects.',
		liveLink: 'https://youtube.com',
		github: 'https://youtube.com',
	},
	{
		image: '/img/myWeb.jpg',
		header: 'My Website',
		about: 'Following projects showcase my skills and experience through real-world examples of my work. Each project is briefly described with links to code repositories and live demos in it. It reflects.',
		liveLink: 'https://youtube.com',
		github: 'https://youtube.com',
	},
	{
		image: '/img/myWeb.jpg',
		header: 'My Website',
		about: 'Following projects showcase my skills and experience through real-world examples of my work. Each project is briefly described with links to code repositories and live demos in it. It reflects.',
		liveLink: 'https://youtube.com',
		github: 'https://youtube.com',
	},
	{
		image: '/img/myWeb.jpg',
		header: 'My Website',
		about: 'Following projects showcase my skills and experience through real-world examples of my work. Each project is briefly described with links to code repositories and live demos in it. It reflects.',
		liveLink: 'https://youtube.com',
		github: 'https://youtube.com',
	},
	{
		image: '/img/myWeb.jpg',
		header: 'My Website',
		about: 'Following projects showcase my skills and experience through real-world examples of my work. Each project is briefly described with links to code repositories and live demos in it. It reflects.',
		liveLink: 'https://youtube.com',
		github: 'https://youtube.com',
	},
	{
		image: '/img/myWeb.jpg',
		header: 'My Website',
		about: 'Following projects showcase my skills and experience through real-world examples of my work. Each project is briefly described with links to code repositories and live demos in it. It reflects.',
		liveLink: 'https://youtube.com',
		github: 'https://youtube.com',
	},
]